### ISSUE TITLE
How to test stores? 

### ISSUE THREAD

**Issue by SuperheroicCoding** [christianalfoni/flux-angular#10]
Thanks first for your great work. I apprechiate that we now can use angular.store and flux.dispatcher.

But do you have an idea how to unittest your stores? 
I ran into problems, when I try execute my karma:jasmine test using flux-angular_2.0.0. stores. 

My test:
```javascript
describe('MyStore', function () {
    beforeEach(module('myApp.myStore'));

    it('should be defined', inject(
        function (MyStore) {
          expect(MyStore).toBeDefined();
        }
      )
    );
  });
```

resulting error: 
MyStore should be defined FAILED
	Error: [$injector:unpr] Unknown provider: AnotherStoreProvider <- AnotherStore
...

I tried to test MyStore. But I got an error about AnotherStore. Looking at your code it seems like all stores in the system must be available.

**Comment by christianalfoni** [comment]
Hi! And thanks very much for the feedback. I have to look into this ASAP.
Feel free to clone and take a look if you want. I am away this weekend, but
I will dive into it as soon as I can :-)

**Comment by christianalfoni** [comment]
Hi again @SuperheroicCoding, 

I have looked into this a bit and will create an example in the readme.

```javascript
describe('store test', function () {
  
  var store, dispatch;
  
  beforeEach(function () {
    module('app');
    inject(function (MyStore, flux) {
      store = MyStore;
      dispatch = flux.dispatch.bind(flux);
    });
  });

  it('It should add new item when dispatching addItem', function () {
    dispatch('addItem', 'foo')
    expect(store.getItems()).toEqual(['foo']);
  });

});
```

**Comment by christianalfoni** [comment]
Hi again!

I just released a new version to help store testing :-)

**Comment by SuperheroicCoding** [comment]
Wow, thanks for your super quick reaction! I will give you feedback soon.
