### ISSUE TITLE
Release files namig

### ISSUE THREAD

**Issue by SLonoed** [christianalfoni/flux-angular#13]
I use bower for manage my deps.
And when i want to update some library, i just user `bower update flux-angular`.
But when you use versions in release files, i need to change files manually.
It make me sad :'(

Other popular bower libs dont use versions in their release files (jquery, angular, angula-mock, restangular, lodash, etc.).

Its not big deal, but expecting behavior for releases.

Thanks!

**Comment by christianalfoni** [comment]
You are perfectly right @SLonoed , I will change to this convention from the next release... which is under way. Thanks for your input :-)
