### ISSUE TITLE
Minifing with ngAnnotate

### ISSUE THREAD

**Issue by SuperheroicCoding** [christianalfoni/flux-angular#14]
When using ngAnnotate before minifing your code, stores are not detected by ngAnnotate. 
Therefore, when defining a store, we can use the ngInject annotation:

```javascript

angular.module('xy').store(createStore);

/*@ngInject*/
function createStore(dep1,dep2,...){...}
```

**Comment by SLonoed** [comment]
Its look like a problem for me.
I use coffee, like this
```
angular.module 'mymodule'
.store (deps1, deps2) ->
    # some code
```

can we use ```.factory``` way in addition to ```.store``` way

**Comment by christianalfoni** [comment]
Hi guys,

Jups, flux.createStore, to be used in factory,  is coming in the next version. It was indeed a bit too ambitious to only have the "store". Thanks for testing and pointing it out :-)

**Comment by christianalfoni** [comment]
Allrighty, new version is released :-)
