### ISSUE TITLE
EventHandler runs 2 times?

### ISSUE THREAD

**Issue by SuperheroicCoding** [christianalfoni/flux-angular#15]
Hi Christian,

maybe you should mention in your readme.me that scope listeners are always called one time initially.

I don't know if this behavior is good. 
My feeling for listeners is, that they should only be called when there events are emitted...

When not using the clean flux way this lead to unforeseen behavior.
If a listener changed values that are not reflected inside the store. The change will happen even if the event was not triggered.

In my case it took a while to find the reason, why my user was always logged out... :). 
My advise would be to invoke the listeners only on corresponding events. 

Have fun! 

Wolfram

**Comment by christianalfoni** [comment]
Hi :-)

It is actually mentioned in the comment on the example "$listenTo", but yeah, should be clearer :-) I agree that $listenTo is an event listener and should only trigger on actual events. If you need to grab state initially you would do that outside of this listener.

Let us call this a bug and remove it! Thanks for bringing it to my attention! :-)

**Comment by christianalfoni** [comment]
Update has been pushed, version 2.1.1.

Thanks for the input @SuperheroicCoding! :-)
