### ISSUE TITLE
karma tests fail with PhantomJS backend

### ISSUE THREAD

**Issue by ngmiller** [christianalfoni/flux-angular#16]
I started to integrate flux-angular into our project today and have hit a wall with karma. For some reason, PhantomJS isn't a fan of flux-angular. Any thoughts as to why? We've been using Travis CI to build and test our PR commits so it'd be nice to keep PhantomJS around.

Test runner output: (from flux-angular root, not our project)
```
$ karma start --single-run --browsers PhantomJS
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket 7F9CnaKZXhVbKx0NhLVA with id 77953079
PhantomJS 1.9.8 (Mac OS X) FLUX-ANGULAR Using the store method should expose the exports object of the store FAILED
	TypeError: 'undefined' is not a function (evaluating 'this.getStore.bind(this)')
... (continues for each flux-angular test)
```

**Comment by sheerun** [comment]
Maybe flux-angular should use its own `bind` internally.

**Comment by ngmiller** [comment]
Argh. Should have searched first. PhantomJS has had this issue for quite a while. https://github.com/ariya/phantomjs/issues/10522

Looks like a fix is marked for their 2.0 release

**Comment by christianalfoni** [comment]
Hi,

Yup, it is a phantomjs issue. I will add this to the README. There is a es5-shim recommended to use with phantomjs.

[ES5-shim](https://github.com/es-shims/es5-shim)

Thanks for creating the issue :-)

**Comment by christianalfoni** [comment]
@sheerun,

Hm, that would also be a solution, but... yeah, I mean... ES5. We should at least be able to use that, as ES6 is on its way ;-)

**Comment by ngmiller** [comment]
@christianalfoni Thanks for the shim link! I'll give that a shot

**Comment by ngmiller** [comment]
Wow, I completely missed this issue in the README *and* in the closed issues. Thanks for putting up with my ignorance!

**Comment by christianalfoni** [comment]
Hehe, that is because I just added it ;-)

Do not feel bad!
