### ISSUE TITLE
Objects in store copied to arrays in controllers

### ISSUE THREAD

**Issue by sebakerckhof** [christianalfoni/flux-angular#17]
Okay, after our discussion on your blog, I'm already back with a question :p. It seemed more appropriate to put it here.

Some useful array functions (eg. indexOf) can't be used because of the deep cloning, because they use strict equality comparison. For example, if I want to update an item in a store, I need a way to find the original item. I could give each item an identifier, but in that case it makes more sense to use an object instead of an array in the store, so I don't need to iterate over the array each time. So I end up with something like:
```javascript
todos : {
  identifier1 : {
    id: identifier1,
    title: 'test todo',
    completed: false
  }
}
```
However, in my controllers and views I often want to use filters, get the length of the scope variable etc, so there I'd rather work with arrays. Since the data is cloned anyway, it would maybe be nice if there'd be an option to copy from object to array or vice versa.

**Comment by christianalfoni** [comment]
Hehe, thats great, I feed on the enthusiasm ;-)

In flux you depend heavily on reference by ID. You are actually encouraged to use temporary IDs if you are waiting for an ID from the server.

I know the feeling of traversing an array to find an item compared to just grabbing it with **indexOf**, but it really does not matter. JavaScript is badass :-)

```javascript
var items = [{
  id: 0
}, {
  id: 1
}];

// The most native way
var id1 = items.filter(function (item) {
  return item.id === 1;
})[0];

// My get function
var getById = function (array, id) {
  return array.filter(function (item) { return item.id === id; })[0];
};

// Underscore
_.findWhere(items, {id: 1});
```

So my point is that I absolutely understand that it feels better to use a map for ID lookup, but t is just a feeling ;-) Using underscore or lodash gives you other possibilities too that quickly becomes useful.

So I do not think it should be flux-angulars job to fix that part, but again, I do see your point :-)

**Comment by sebakerckhof** [comment]
Thanks, but I was more thinking about performance impact than about programming convenience. It's because in TodoMVC one can set all tasks as completed or not completed at once.
What this does is in the normal angular TodoMVC is loop over the array (in the controller, so over the array in the scope) and set the completed flag to true for each item.
Let's say you have N todo items. This would require you to iterate N times over the array to find the correct index for each element (well in fact iterate over (n*(n+1))/2 elements).
Now everytime you update an item, all controllers that listen to the store will get a clone. Let's say you have 3 controllers, but they only listen to 50 items. Still that is 3*50*N elements that need to be cloned on to of the (n*(n-1)/2) lookups.

A solution would be to create an action 'setAllCompleted' which lets the store deal with setting all items completed in one loop before it emits a change event to the controllers. But this doesn't seem very scalable as you'll soon end up with a jungle of actions.

**Comment by sheerun** [comment]
You can create hash index for items in store, and create getter that uses this index.

With lodash it would be:

```
this.itemsById = _.indexBy(this.items);
```

You can also refresh / modify this index on actions.

**Comment by sheerun** [comment]
You can also use binary search like `_.sortedIndex` that is bounded by `log(n)`

**Comment by christianalfoni** [comment]
It is also worth mentioning that in flux you really do want lots of actions (dispatching to business logic). You do not want that logic in your views (controllers). Views should be as dumb as possible. Even though it can be a jungle, the jungle is at least flat :-) Views are nested in each etc., which makes things more complex.

So in the case you are referring to you really would want to create a "setAllCompleted" action. That makes it possible for any other view, or whatever really, do to the exact same thing using the same business logic.

I challenge you to create as many actions as possible, dispatching to business logic. You should feel better when having that logic contained in your stores, rather than in your controllers :-)

**Comment by christianalfoni** [comment]
Old issue, closing
