### ISSUE TITLE
flux is not dispatching if called from resolve on ui-router on the FIRST page load

### ISSUE THREAD

**Issue by nozer** [christianalfoni/flux-angular#20]
Hi, 

I am using ui-router with flux angular for a single page app. I have a little problem with flux not dispatching on page load. 

Imagine I have the following `$state` config for my ui-router

```
.state('account.home', {
    url: '/home',
    controller: 'HomeCtrl',
    templateUrl: '...',
    resolve: {
       preloaded: function(flux, constants){
           // being super simple here just to focus on the problem 
           flux.dispatch(constants.actions.GROUP_POPULATE);
           return 1;
        )
    }
...
```

That dispatch won't fire when the page is reloaded/refreshed to .com/account/home (I have a console.log in my .store service to test). However, after page is loaded, if i navigate to some other url on the single page app like .com/account/profile and then go back to .com/account/home with a click (state change), it will fire. It just won't fire on initial load. 

The order of my scripts are like this:
```
angular.js
flux.angular.js
ui-router.js
<all of my controllers/directives/services etc>
myMainModule.run.js
```

Any suggestions?

**Comment by christianalfoni** [comment]
Hi there! 

Before setting up an example locally. Does the "preloaded" method trigger at all? So, the line before flux.dispatch, does that run on first page load?

**Comment by nozer** [comment]
Yes, it does. I forgot to put that in the example above but it does (I did console.log and saw)

**Comment by christianalfoni** [comment]
Aha, I think I know whats wrong. The stores has not been instantiated yet. Initially this was done automatically, but it was removed again because it was considered an edge case. This might prove I'm wrong :-)

Could you try injecting your stores into the run method?

```javascript
.run(function (MyStoreA, MyStoreB) {
  // Do not have to do anything
});
````
This will instantiate the stores and attach them to the dispatcher. If this fixes it I can put back the "auto-instantiate" thingy :-)

**Comment by nozer** [comment]
Hi, yes it works when I inject the store. You can add this case to the documentation or put it back so it won't cause headache for others. 
Thanks a lot for the solution!

**Comment by christianalfoni** [comment]
Okay, released new version where stores are pre-injected now. that way you do not even have to check the readme :-)

**Comment by nozer** [comment]
Awesome! Thanks a lot Christian!
