### ISSUE TITLE
Little hint for monkeypatch

### ISSUE THREAD

**Issue by SuperheroicCoding** [christianalfoni/flux-angular#21]
Hi Christian,

take a look at this example: 

http://www.bennadel.com/blog/2775-monkey-patching-the-q-service-using-provide-decorator-in-angularjs.htm

Maybe you can use decorators to monkeypatch angular.

Have fun!
Wolfram

**Comment by christianalfoni** [comment]
Thanks for the link :-)

I will check this out for the next version!

**Comment by christianalfoni** [comment]
This only seems to work on services only, but very nice to know! Let me know if I misunderstood anything here :-)
