### ISSUE TITLE
Unable to load the node module

### ISSUE THREAD

**Issue by ajatakia** [christianalfoni/flux-angular#24]
Hi,

I am trying to consume your module in a project and I have following statement in my app.js

var flux = require('flux-angular');

When I run my watchify command: watchify starting_file.js -o dist/bundle.js -v -d .

I get following error:

Error: Cannot find module 'flux-angular' 

When I run the browserify command:  browserify starting_file.js -o dist/bundle.js -d

I get below error:

Error: Cannot find module 'flux-angular' from '/Users/user/Documents/CF/CF.Common/Client.Components/app'
    at /Users/user/Documents/CF/CF.Common/Client.Components/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:50:17
    at process (/Users/user/Documents/CF/CF.Common/Client.Components/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:119:43)
    at /Users/user/Documents/CF/CF.Common/Client.Components/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:128:21
    at load (/Users/user/Documents/CF/CF.Common/Client.Components/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /Users/user/Documents/CF/CF.Common/Client.Components/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /Users/user/Documents/CF/CF.Common/Client.Components/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:108:15)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/user/local/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
npm ERR! CF.Common@1.0.72 start: `browserify start_file.js -o dist/bundle.js -d`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the CF.Common@1.0.72 start script 'browserify start_file.js -o dist/bundle.js -d'.
npm ERR! This is most likely a problem with the CF.Common package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify start_file.js -o dist/bundle.js -d
npm ERR! You can get their info via:
npm ERR!     npm owner ls CF.Common
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

I am trying to consume the Version 2 of your library. 

can some one please help.

**Comment by christianalfoni** [comment]
Hi @ajatakia ,

This seems to be a browserify error. I have used browserify to build the thing, so it seems a bit strange :-)

I just have to ask one question first, flux-angular is installed in the node_modules folder of the project?

And second question. Does this only happen to flux-angular? If you require an other module, everything works?
