### ISSUE TITLE
Implement component into v2

### ISSUE THREAD

**Issue by jolafrite** [christianalfoni/flux-angular#25]
Hi,

First, thanks for the great job, this library is stunning.
I still have things to figure out but to have the flux pattern available in angular, is awesome.

1- In your first version of the library, you gave two examples, one using a normal angular controller and a second one using component (a preconfigured directive).
I'm wondering if you can implement back  component into version 2 (Users can choose to use controller or component).
So I don't need to implement it back in every new version by myself.

2- Do you have a code example using this library more advanced than a todo list, with multiples models and  relations.

3- Did you try to implement React components with angular-flux ?

**Comment by christianalfoni** [comment]
Hi there @jolafrite and thanks for the feedback! :-)

1. That is a good point! Yeah, I will definitely consider this

2. Hm, I currently do not have any code to share on that, but I can create one. Give me a few days and I will create a demo app

3. Well, if we put React JS in here there really is not much Angular left :-) React JS is also quite large, 130 kb, add angular on top of that which is another 130 kb. But please discuss this further if you want. This is more of a principle to me, might be lots of scenarios I am not thinking of :-)

**Comment by SuperheroicCoding** [comment]
To learn about flux I played around with colors. But it's a little bit more complex than the todo-List. 
Colorflux: http://embed.plnkr.co/dZhigG/preview
I learned a lot and of cause it's not perfect. As always there is much room for improvements and discussions. Looking forward for your opinion... Have fun!

**Comment by jolafrite** [comment]
@SuperheroicCoding Thanks for your code, I will definitely have a look
@christianalfoni Maybe integrate ReactJs is not the best thing to do. 
From this library I was interested by the virtual dom part. 
So when you have a long list with a lot of watchers, how do you handle that ?

**Comment by christianalfoni** [comment]
Hi @jolafrite ,

Virtual DOM is awesome! But the Angular team has done a pretty good job with Angular too. They will probably switch to a virtual DOM for next release :-)

You mean if you have like 100 items and 5 different controllers is grabbing that on each change? Technically flux-angular will deep clone the list of 100 items 5 times. That is of course not very performant, but remember that you use exports to grab that list. You rarely want to grab all 100 items 5 different places. Maybe you only grab one of them, 10 first etc. That way is is quite performant.

The alternative is using immutability. I am looking into it, but there are some challenges. Like with immutable-js it is a lot more performant to do the current cloning that e.g. immutable.fromJS(items);. What you really want to achieve is just returning the list in an immutable wrapper, but then you can not use it directly in a template.

A different approach is to only change the reference of objects and arrays in the trees if they update. That will avoid the two way databinding from triggering and making sure you will have to specifically grab that new state form the store. The problem though is that the new list will be shared by all controllers fetching it. If they were to mutate the list the two-way-databinding would trigger and cause unexpceted behavior.

The plan is to try it out. Create an immutable API for the store. Something like:

```javascript
store.('MyStore', function () {
  return {
    items: [{label: 'foo'}, {label: 'bar'}],
    addItem: function () {
      this.push('items', {label: 'banana'});
    }
  };
})
```
Running that code will of course push the new object into the array, but it will also change the array reference on items by doing e.g. a `items = items.slice(0)`. Whats nice about this is that it can also automatically trigger an event based on the first argument. So a push to "items" will trigger an "items" event. Kinda nice. What is a bit unclear now is if Angular does any mutations to the arrays/objects, which I think it does. There is this crazy $$hash property that seems to be added. This would then be shared across all controllers that have grabbed the array/object. And that sucks :-)

So I thought I would just implement this as a BETA API on top of the current API and let people try it out with caution. If it works it will be a hell of a lot faster than the cloning :-)

**Comment by jolafrite** [comment]
Cool I will give it a try.
I'm also quite impatient to see your demo app

**Comment by christianalfoni** [comment]
Hi,

Just wanted to let you know that I have been working on a lib: https://github.com/christianalfoni/immutable-store and an article using that lib to use Angular in a pretty cool way. Will invite to a discussion as soon as the article is out :-)

It will also have the TODOMVC demo app included.
