### ISSUE TITLE
this.exports error: cannot read property of undefined.

### ISSUE THREAD

**Issue by nozer** [christianalfoni/flux-angular#26]
Hi

Imagine a store named dataStore defined like this: 
```
return {
data:[],
exports: {
   func1: function(){
      return this.data;
   },
   func2: function(){
      return this.exports.func1();
   },

   func3: function(){
      return this.exports.func2();
   }
}
}
```

If I do dataStore.func3(), I would get an error in func2 that says 
```cannot read property `func1` of undefined.```
  
I assume `this` bindings got lost somewhere. Any fixes?

UPDATE: 
Right now, I am bypassing the problem by doing `this.exports.func2.call(this)` in func3 and `this.exports.func1.call(this)` in func2. 

Thanks

**Comment by christianalfoni** [comment]
Hi there!

Yes, of course, have to hard bind those. Will make a fix for it :-)

**Comment by nozer** [comment]
Thank you Christian! :)

**Comment by christianalfoni** [comment]
Fixed, coming on next release, thanks for the feedback :-)
