### ISSUE TITLE
Async dispatch race condition

### ISSUE THREAD

**Issue by ngmiller** [christianalfoni/flux-angular#29]
Hey there!

(Hopefully) quick question relating to the nature of action dispatches and asynchronous event handling. In my effort to support user initiated browser refreshes I've settled upon a convention where controllers are responsible for populating their injected stores by calling an async service to fire off dispatches with successful responses.

```js
.controller('example', function ($scope, myService, myStore) {
    
    myService.getThing();
    myService.getAnotherThing();

    $scope.$listenTo(myStore, function () {
        ...
    });

});
```

where `myService` is defined like so:

```js
.factory('myService', function ($http, flux) {
    return {
        getThing: function () {
            $http.get('/api/call').then(
                // success
                function (response) {
                    flux.dispatch('someActionA', response.data);
                },
                // error
                function (response) {
                    // custom error handling
                }
            );
        },

        // defined similarly to getThing() above
        getAnotherThing: function () { ... }
    };
});
```

With this convention and some work with localStorage, I'm able to support full page/view/data reloads within the single-page app environment.

But, I think I've hit a wall with a race condition. It seems like the $http promise from the second async call in the controller is resolving while the dispatch from the first is executing (or vice versa), which results in: "cannot execute 'someActionB' while 'someActionA' is executing"

So with that, am I handling the async data responses in a reasonable way? I figured one option was to wrap dispatches into a queue, but wanted to get your thoughts before going down that route. Thanks!

**Comment by christianalfoni** [comment]
Hi @ngmiller!

You should join our discussion at https://github.com/christianalfoni/flux-angular/issues/28. Looking into more evolved FLUX patterns. The article has a demo that does a localStorage thingy, which is kinda awesome.

Anyways, to your problem at hand! Hm, this seems a bit strange. Is the problem consistent? It always happens? I think the error message is related to not allowing one action to synchronously trigger an other action... but that is not the case here. Those two responses happens asynchronously. Promises themselves are async by default, which makes it even weirder. 

I think you are reasoning about this in a good way. Having a service grabbing the data and dispatching it to the store. Could you verify that I am reasoning about this correctly? If so I have to create an example locally. 

How does the code in the **someActionA** and **someActionB** look?

**Comment by ngmiller** [comment]
Hey @christianalfoni! Thanks for your quick reply.

> I think you are reasoning about this in a good way. Having a service grabbing the data and dispatching it to the store. Could you verify that I am reasoning about this correctly?

That's how I'm viewing it. "Waiting" for data to come in from an async call and then dispatch it out seems like the perfect job for a service.

I did some more digging into my issue and found that I was trying to access attributes from my store data that didn't exist (the difference of one capital letter!), causing an exception to be raised during the dispatch of the first action in the sequence above. Have you found any nice ways of recovering from an exception during an action dispatch?

Anyway, the apparent problem I come across was my fault. My relationship with javascript is love/hate :)

Thanks for taking the time! I'll certainly take a look at the discussion you've pointed me to!

**Comment by christianalfoni** [comment]
Hi again @ngmiller ,

Good to hear that you figured it out :-)

About the recovering. I think about it like this. If you have an exception related to action dispatching you have a bug in your application. Instead of creating recovery code, you should create a test instead ;-) But that is just my opinion of course
