### ISSUE TITLE
$listenTo not triggering $digest when using "controller as" and "this"

### ISSUE THREAD

**Issue by ericmcgregor** [christianalfoni/flux-angular#30]
I was curious if i'm doing something wrong here.  I'm listenting to my store from my controller and using that controller on my directive.  I'm using the "bindToController" which wants you to add your data to "this" in your controller instead of $scope.  My problem is, when my store emits a change, it is not getting updated from $scope.$listenTo unless i run a $timeout.  Here is my setup:

.directive('bigList', function(){
  return {
    controller:"ListCtrl",
    controllerAs:"ctrl",
    bindToController: true,
...etc...

.controller('ListCtrl', function($scope, ListStore, $timeout){
this.state = [];
  $scope.$listenTo(ListStore, function () {
    this.state = ListStore.getState();
    $timeout(function(){},0);
  }.bind(this));

if I don't add the $timeout, it won't get picked up by the apply cycle in some cases.  if i add $scope.$digest(), it will tell me that the digest cycle is already running.  

I'm wondering if this is because i'm using "this" instead of $scope for my controller data.  Or if the $listenTo helper isn't triggering a digest cycle in some cases.

This does update properly in some instances.  For example, in my init function i'm making an $http call and emiting the change in the success callback.  i know $http triggers the digest.  But if i use an action that changes my data model and emits a change, the $listenTo won't see it.

any thoughts would be super helpful!

**Comment by christianalfoni** [comment]
Hi @ericmcgregor !

The $digest loop will trigger after the events are triggered, though for some reason not here. I have to check it out some more, but you can also do `$scope.$apply()`, which feels a bit less hacky :-)

**Comment by christianalfoni** [comment]
Hi again!

The reason is that the controller does not inherit from $scope using the bind property. I can not get a hold of the controller prototype so I would have to wrap this up in a component. You have just made a case for using a wrapper here :-)

Working on new version now, so hopefully this will be fixed with a .component() wrapper!

**Comment by ericmcgregor** [comment]
Ah... i think i follow you there.  My understanding was that structuring your directives in this manner, by using the controller to get the data and functions and exposing it back to the directive using "this" instead of $scope was the best practice.  (especially in light of angular 2.0)  I have historically not approached directives this way, but am making an effort to really try and stick with best practices.  So, i thought that there might be some cause coming from using 'this' vs '$scope'.

In some cases this does work as is without a $timeout... but i believe that's coincidental to when an $apply cycle is being run by something else.  are you suggesting a .component() monkey patch to take the place of a .controller to force an apply cycle on this?

**Comment by christianalfoni** [comment]
Hi there!

Have a look at the discussion at: https://github.com/christianalfoni/flux-angular/issues/28#issuecomment-76406342. Give me some feedback an I am sure we will figure this out :-)

**Comment by christianalfoni** [comment]
Hi again,

It seems that people think that "component" is outside the scope of flux-angular. I kinda agree with that.

But I tested this and I am not sure what is wrong on your side, it works here. Did you remember to trigger `emitChange()`?

**Comment by christianalfoni** [comment]
Closing it as it is old
