### ISSUE TITLE
Handle store relations with async calls.

### ISSUE THREAD

**Issue by jolafrite** [christianalfoni/flux-angular#31]
Hi

I would like to have your point of view about how to use the flux pattern and handle store relations with async calls.

Example : 

this.$listenTo(AuthStore, 'auth.loadCurrentUserSuccess', function () {
    UserCompaniesAction.loadCompanies();
});

In this component code we are waiting the app to load the current user (Async) to be able to load the user companies.
They are both triggering a dispatch change.

So I get the error :
Error: Cannot call dispatch while another dispatch is executing. Attempted to execute 'load_companies_user' but 'load_current_user_success' is already executing.

So the previous dispatch did not finish when the app dispatch load_companies_user.

I don't want to use a setTimeout because it's ugly
So how would you refactor this code to respect the flux pattern ?

**Comment by jolafrite** [comment]
I guess it is the same question as the issue titled "Async dispatch race condition"

**Comment by christianalfoni** [comment]
Hi @jolafrite,

I see your point here. I would consider having an action initializing your application. So you have one action that does something like: 

```javascript
var initAction = function (flux) {
  flux.dispatch('loadingUser', true);
  getUser()
    .then(function (user) {
      flux.dispatch('loadingUser', false);
      flux.dispatch('user', user);
      flux.dispatch('loadingCompanies', true);
      return getCompanies();
    })
    .then(function (companies) {
      // etc.
    }); 
};
```

This also gives you a very good overview of what actually happens when your application runs. Instead of spreading it between different controllers.

Would that make sense? :-)

**Comment by jolafrite** [comment]
I was thinking about doing it this way

Thanks

**Comment by christianalfoni** [comment]
Great!
