### ISSUE TITLE
Bump immutable-store

### ISSUE THREAD

**Issue by jrust** [christianalfoni/flux-angular#35]
Could you release a version with the latest immutable-store?  The ability to set primitives will allow me to give it a much more more thorough run.  Thanks.

**Comment by christianalfoni** [comment]
I was hoping to get that component discussion nailed first. You have any thoughts on that? https://github.com/christianalfoni/flux-angular/issues/28

Considering releasing it as BETA API

**Comment by christianalfoni** [comment]
Okay, bumped :-)

**Comment by jrust** [comment]
:+1:

**Comment by jrust** [comment]
Actually, looks like bower.json got bumped to `2.2.1` instead of `2.3.1`

**Comment by christianalfoni** [comment]
Well, thats embarrassing ;-)

Fixed now

**Comment by jrust** [comment]
Looks like you also need to add a `2.3.1` tag to the repo in order for bower to find it

**Comment by christianalfoni** [comment]
I do not know what I have been smoking :p Its updated now!

**Comment by jrust** [comment]
Works :smile:

**Comment by christianalfoni** [comment]
Thanks for the tip :+1:

**Comment by jrust** [comment]
I kind of hate to ask but could you bump it again?  We're migrating our app and using the immutable stuff quite extensively and I'm afraid the bugs that were recently closed in immutable are going to bite us.

**Comment by christianalfoni** [comment]
Hi @jrust ,

Which fixes are you referring to? Running flux-angular 2.3.2 with immutable-store 0.2.3 is the latest?

**Comment by jrust** [comment]
Dangit, I didn't even notice 2.3.2.  You're way ahead of me, sorry for the noise, and thanks for your work!

**Comment by christianalfoni** [comment]
Hehe, no worries :-)
