### ISSUE TITLE
Listened event on scope is not being called

### ISSUE THREAD

**Issue by nozer** [christianalfoni/flux-angular#38]
Hi!
I am using version 2.2.0 of flux-angular. 
I am triggering an event like like this from my store named `tc3Store`
```
this.emitChange('offline')
```

And when I try to listen to changes like this, it won't trigger
```
$scope.$listenTo(tc3Store, 'offline', function(){
    console.log('gone offline'); // won't show anything 
});
```

However, if I listen to it like this (a generic listen), it triggers
```
 $scope.$listenTo(tc3Store, function(){
     console.log('tc3store change');
 });
```

What am I doing wrong?

**Comment by nozer** [comment]
Oh, I just realized that I should do `this.emit('offline')` instead of `.emitChange`.

**Comment by christianalfoni** [comment]
Exactly :-)
