### ISSUE TITLE
$listenTo multiple stores

### ISSUE THREAD

**Issue by MyBoon** [christianalfoni/flux-angular#39]
Does it will make sense to have a way to listen to an array of Stores, and only provide one unique callback. I sometime see things like: 

```js
$scope.$listenTo(StoreA, function () {
    set();
});
$scope.$listenTo(StoreB, function () {
    set();
});
$scope.$listenTo(StoreC, function () {
    set();
});
```

could be replaced by :

```js
$scope.$listenTo([StoreA, StoreB, StoreC], function () {
    set();
});
```

I can implement this and do a pull request. Just wanted to make sure it's something you guys want as a design =). Let me know!

**Comment by christianalfoni** [comment]
Hi @MyBoon,

Yeah, this definitely makes sense. Would love a pull request on that :-)

**Comment by MyBoon** [comment]
Cool. Let me hack that today and make you a pull request by tonight =)

**Comment by christianalfoni** [comment]
Great :-)
