### ISSUE TITLE
Support max listener configuration

### ISSUE THREAD

**Issue by pramodsankarl** [christianalfoni/flux-angular#42]
Hi,

   When a particular store change is being  listened by more than 10 different places(EventEmitter default limit -`defaultMaxListeners`- is 10), i get the following error from the EventEmitter.

 **(node) warning: possible EventEmitter memory leak detected. 3 listeners added. Use emitter.setMaxListeners() to increase limit.**

Which traces down to this comment in the source:
> // By default EventEmitters will print a warning if more than
                // 10 listeners are added to it. This is a useful default which
                // helps finding memory leaks.
                //
                // Obviously not all Emitters should be limited to 10. This function allows
                // that to be increased. Set to zero for unlimited.

and the configuration is a pretty useful use case i believe.Is there a better way to configure this (other than `this.setMaxListeners(n)` within the store initialize method)? Probably exposing a provider (FluxProvider) function to specify the listener limit for required stores as a dictionary or specifying the settings in the store itself, example:

    .store('userStore', function(){
      var _user = "";
      return{
         maxListeners:20, //Max listeners here or within a generic config key in order to be able to specify any other configuration
         userChanged:function(user){
             _user = user;
             this.emitChange();
          },
        exports:{
          getData:function(){
            return _user;
          }
        },
        handlers:{
          'userChanged':'userChanged'
        }
      }
    });

and just to fix it in the **[code pen](http://codepen.io/pramodsankarl/pen/QbjBdP)**, i made this change just to showcase in the demo.

    // Call the constructor of EventEmitter2
     EventEmitter2.call(this, {
        wildcard: true,
       maxListeners: spec.maxListeners
    });

Appreciate any help on this.

**Comment by christianalfoni** [comment]
HI @pramodsankarl ,

So sorry about late reply, but have been deep down into a project that last week.

There is a provider already so I can add a method to increase the number of listeners. Seems ok?

**Comment by pramodsankarl** [comment]
@christianalfoni  Thanks for taking a look. That would be awesome. While thinking about this, since we can have different listener settings for each store (Since each store has its own Emitter instance) should the provider function support setting one globally for all stores and if needed for specific stores? Does that make sense?

**Comment by christianalfoni** [comment]
Lets get into some syntax for this :-)

```js
angular.module('app', ['flux'])
.config(function (fluxProvider) {
  fluxProvider.useCloning(false);
  fluxProvider.setMaxListeners(20);
  // or
  fluxProvider.setMaxListeners({
    'myStoreA': 20,
    'myStoreB': 15
  });
});
```
Would that solve it you think? I think it is the most fitting place and if I understand you correctly this should cover it?

**Comment by pramodsankarl** [comment]
Yes, This is exactly what i meant... Thanks @christianalfoni

**Comment by christianalfoni** [comment]
Okay, released new verison. https://github.com/christianalfoni/flux-angular/releases/tag/v2.4.0

**Comment by pramodsankarl** [comment]
@christianalfoni  Thanks again for this addition. Just a quick question, when you do:

    else if (maxListeners && maxListeners[name]) {
      this.setMaxListeners(maxListeners[name]);
    }

it could so happen that if we set maxListener to 0 (unlimited) eg: `fluxProvider.setMaxListeners({'myStore': 0})` the falsy check will end up not setting it, instead do you want to check for just the existence of property in the object?

**Comment by christianalfoni** [comment]
ah crap, I remembered it on the other one though :-D

But yeah, I think we are good... you would never set 0 listeners ;-)

But will fix it so it will be part of next release. Thanks for pointing it out!

**Comment by pramodsankarl** [comment]
Yeah Emitter considers 0 to be unlimited, Using that would be an edge case but still don't want to block that option. Next one should be fine.. Cheers!!

**Comment by christianalfoni** [comment]
Okay, thanks for the input, I will make sure this is part of next release!
