### ISSUE TITLE
Breaks the app when store is registered but respective module is not in the dependency list anywhere

### ISSUE THREAD

**Issue by pramodsankarl** [christianalfoni/flux-angular#43]
Hi @christianalfoni ,

It seems like there is bug due to injector invocation on preinjectionList. When we register a store they get registered and added to the preInjection list. But if we do not list the respective module that contains this store as depdendency anywhere at all, it throws unknown provider error due to the fact that `$injector.invoke` on the preinjection list contains this store too but is not available in the module cache. I believe it should not cause an error, i would be interested to know why is there an explicit injector invocation (even if i remove it, still does work).

Steps to replicate:

Create a store:

    function UserStore(){
      var _user = "";
      return{
         userChanged:function(user){
             _user = user;
             this.emitChange();
          },
        exports:{
          getData:function(){
            return _user;
          }
        },
        handlers:{
          'userChanged':'userChanged'
        }
      }
    };

Register it under a module:

    angular.module('myStores',[]).store('userStore',UserStore);

Create your app

     angular.module('app', ['flux'])
       .controller('controller', function(flux){
       this.name="Hey";
    });

now this will throw error,

>Uncaught Error: [$injector:unpr] Unknown provider: userStoreProvider <- userStore

 to fix it you have to list `myStores` as dependency in `app` even though you don't use it (yet) i.e

     angular.module('app', ['flux','myStore'])...

**[Demo](http://codepen.io/pramodsankarl/pen/QbdvBW?editors=101)**

This situation can happen more often during development on a large code base and different developers working on it. The error is misleading too because first thing every one will check is "where have i injected userStore without injecting the module". Can this be handled? Thank you!!

**Comment by christianalfoni** [comment]
Hi there,

I have been going a bit back and forth on this issue. Initially I thought it was a good idea to pre-inject the stores to avoid situations where one store depends on an other and you only inject the first one, but it caused unwanted behaviour when testing. Then I chose to only pre-inject when not testing... but that seems to cause this situation. Hm hm...

Maybe it should be a specific option instead? 

```js
angular.module('app', ['flux'])
  .config(function (fluxProvider) {
    fluxProvider.injectStores();
    fluxProvider.injectStores(['storeA'], 'storeB']);
  });
```

What do you think?

**Comment by pramodsankarl** [comment]
Hi, Thanks for responding. I did not quite understand the issue:  _"Initially I thought it was a good idea to pre-inject the stores to avoid situations where one store depends on an other and you only inject the first one"_. 

I commented out the line `$injector.invoke(preInjectList.concat(function () {}))` in the **[Demo](http://codepen.io/pramodsankarl/pen/bdqORW)** and just added another store which is being required by userStore which is the only one injected, i don't see any issues though. Please correct me if i am wrong or if i understand the problem incorrectly. I feel that explicitly setting the injection list with `fluxProvider.injectStores(['storeA'], 'storeB']);` does not seem to be a natural way and will be an additional overhead.

**Comment by christianalfoni** [comment]
Hi again @pramodsankarl ,

I should give you some more details here :-)

If one store uses the "waitFor" method and the other store is not injected it will fail. That is why it preinjects the stores. I could of course just throw an error there instead for those situations. So if such a scenario occurs you would just have to make sure that the store in question is actually injected into the app when initiating.

What do you think?

**Comment by pramodsankarl** [comment]
Hi @christianalfoni 
> I could of course just throw an error there instead for those situations. So if such a scenario occurs you would just have to make sure that the store in question is actually injected into the app when initiating.

Did you mean list the module that contains the store as dependency, if so I :thumbsup: this. I think that would be the right behavior and no confusion and in alignment with the natural usage. If not, and you meant inject the store listed in the waitFor itself (in a controller/provider etc) before throwing error, could you not still check if the store listed in the waitFor can be retrieved (instantiated) from the injector lazily?

**Comment by christianalfoni** [comment]
Hi again,

Hm, lets take a look at this with an example :-)

```js
.store('CommentsStore', function () {

  return {
    comments: [],
    handlers: {
      'addComment': 'addComment'
    },
    addComment: function (comment) {
      this.waitFor('NotificationStore', function () {
        this.comments.push(comment);
        this.emit('comments.add');
      });
    },
    getComments: function () {
      return this.comments;
    }
  };

})
.controller('MyCtrl', function (CommentsStore) {

});
```
So:

1. With current logic "NotificationStore" will already be pre-injected and this will work, even though the controller and the store does not inject "NotificationStore"

2. The above code could instead throw an error saying: "CommentsStore is waiting for a store that is not yet injected. Please inject NotificationsStore"

3. I suppose flux-angular could automatically inject the store if it is not already injected, not throwing an error, but just work as you would expect

You think option 3. is best? I am leaning towards it, though I have to check a couple of things :-)

**Comment by pramodsankarl** [comment]
@christianalfoni Apologies for the delayed reply. Yes that would be perfect, i am up for option-3 as well. So that as a consumer, i do not need to worry about injecting it just for the sake of injecting. If the dependent store is not available in the injector cache (if the module the store belongs to is not listed as dependency in the module cache) you can throw the error.

**Comment by christianalfoni** [comment]
Hi again!

Okay, taking a look at this now :-)

**Comment by christianalfoni** [comment]
Hm, okay, I looked a bit more into this. The problem is that a dispatch occurs first, then the waitFor triggers. If the store is injected during the "waitFor" the dispatch is already running, overlooking the newly injected store.

I think the best solution here is to just run a "console.warning" when it notices a missing injection. That seems okay to you?

**Comment by pramodsankarl** [comment]
Hi @christianalfoni . Apologies for not following up on time, its been a long time. Yes i think a warning should just be good enough to inform the developer. So overall we will no longer have this pre-injection logic, correct? and no additional changes on the consumer end right? Thanks for reading this and appreciate your help!

**Comment by christianalfoni** [comment]
Hi again @pramodsankarl,

Sorry for my late reply :-)

Yes, instead of forcing something behind the scenes it seems better to let the developer structure the application in a way that makes sense.

With current change the following will happen:

- No pre-injection
- If you dispatch and there are stores not injected yet it will give a warning with the name of those stores, as flux-angular does not know what stores you are trying to dispatch to. Only dispatcher knows that. The dispatch will still run and maybe end in an error, as the dispatch has no store to reach. But now you have gotten a good warning explaining the issue
- If a `waitFor` is used on a store that is not injected yet it will throw an error, as now it knows exactly what store is missing

Sorry if this is contradictory to what we first discussed, but I have been swamped with other projects. Good thing is that I am now working 100% open source and on own projects. Got loads more time :-)

**Comment by pramodsankarl** [comment]
@christianalfoni :thumbsup: Perfect, very explicit and no magic. Exactly what i was looking for in terms of implementation as well. Thanks a lot for spending some time into this :)

**Comment by christianalfoni** [comment]
Okay, releasing new version now
