### ISSUE TITLE
flux-angular IE8 problems

### ISSUE THREAD

**Issue by Booyanach** [christianalfoni/flux-angular#50]
Now, I understand that IE8 will be getting dropped relatively soon (January 2016), but since we're still not there, yet, is there any chance that we could change those Object.defineProperty calls in the code? (they're not suported in IE8) Otherwise would mean that this plugin doesn't fully support Angular 1.2.X's capabilities (as in being IE8 compliant)

**Comment by christianalfoni** [comment]
Hi @Booyanach , yeah, we should fix this. But is it: `Object.getOwnPropertyDescriptor` that breaks it? The `defineProperty` is inside an if statement, so should never be called on IE8.

**Comment by jrust** [comment]
Looks like you can get around this by adding [es5-shim](https://github.com/es-shims/es5-shim) which adds a shim for `getOwnPropertyDescriptor`
