### ISSUE TITLE
Suppress webpack `Critical dependencies` warning message

### ISSUE THREAD

**Issue by pribilinskiy** [christianalfoni/flux-angular#54]
Requiring `flux-angular` with webpack introduces a warning message in console

```
Critical dependencies:
1:435-442 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
```

**Comment by christianalfoni** [comment]
Which version are you running? It should not do that anymore. Package.json points to the source file now. Hm, let me know :-)

**Comment by pribilinskiy** [comment]
It was solved by adding `noParse: [ /flux-angular/ ]` in `webpack-config`

**Comment by christianalfoni** [comment]
Glad you figured it out, though it seems really weird. As if it is using the release version of flux-angular, not the one in `src/flux-angular`. Need to know more about the setup to investigate further, though it is a technicality. It is the same code running :-)

Let me know if you want to share some more config to investigate further or we can just close the issue
