### ISSUE TITLE
No digest after server data was retrieved.

### ISSUE THREAD

**Issue by Mishurin** [christianalfoni/flux-angular#62]
Guys, I am not sure if angular should update anything after dispatcher emits change on immutable collection. The reason is not syncronized digest and event emission of the flux dispatcher.

Here is my controller. Just trying to implement your solution

`
export class LinksListController {

    private scope: any;
    private lStore: any;

    public static $inject: Array<string> = ['LinksStore', '$scope'];

    public links: Array<any> = null;

    constructor(LinksStore: any, $scope: any) {
        this.scope = $scope;
        this.scope.$watch(() => {
            return this.links;
        }, (a, b, c) => {

        });
        this.lStore = LinksStore;
        this.scope.$listenTo(this.lStore, this.setLinks);
    }

    private setLinks = (): void  => {
        this.links = this.lStore.links;
    }
}
`

Any suggestions?  Thank you in advance!

**Comment by jrust** [comment]
Can you give more context about what is going wrong and what you're trying to achieve?  You are right that the $digest cycle will not be triggered just by the store emitting an event.  However, the store will only be updated as part of the digest cycle (e.g. ng-click event triggers flux.dispatch) and thus the $watch would see the `this.links` with a new value.  So, also include how you are triggering a change of the state in `lStore`.

**Comment by Mishurin** [comment]
I see. Here is my context. Probably my initialization is not correct. Here is my store implementation. I expect that my views will be notified after state will be reset according to the ajax response, that is after 

> store.state.set('links', response.Items);


`
LinksStore .$inject = ['ResourceFactory', '$log'];

export function LinksStore (ResourceFactory: ResourceFactory, $log: ng.ILogService) {

    var resource: IResourceBase<IExternalWebLink> = ResourceFactory.create<IExternalWebLink>('externalweblinks', true);

    return {
        initialize: function () {

            var store = this;

            this.state = this.immutable({
                links: []
            });

            resource.odata().query().$promise.then((response: any) => {
                store.state.set('links', response.Items);
            }, (e) => {
                $log.debug('HTTP Service Error: ', e);
            });

        },

        handlers: {
            'addLink': 'addLink'
        },

        addLink: function (link) {
            this.state.push('links', link);
        },

        exports: {
            get links() {
                return this.state.get('links');
            }
        }
    };
}
`

**Comment by Mishurin** [comment]
Of course if I trigger the digest clicking on a button view will be updated as well. However I want data be rendered on set.

**Comment by jrust** [comment]
Hmm, that looks like it should work b/c it is setting `links` as part of the ajax digest cycle.  What happens if you put this in your application config:
```
fluxProvider.setImmutableDefaults({ asynchronous: false });
```

**Comment by Mishurin** [comment]
That is worked! :) Thank you, man! It worked. However new angular wants using injector for configuration. It makes sence to change documentaion concerning fluxProvider. I mean using it like:
`
fluxConfig.$inject = ['fluxProvider'];

export function fluxConfig (flux: any): void {
    flux.setImmutableDefaults({ asynchronous: false });
}
`

**Comment by jrust** [comment]
Thanks, good to know.  It makes sense since baobab, by default, tries to batch up changes and dispatch the event on the next tick and that is out of the angular digest cycle.  Surprised I haven't seen it yet, but I'm guessing it's because as the app grows in size the digest cycle gets more stuff mixed into it.
