### ISSUE TITLE
Best Way to object update in a collection

### ISSUE THREAD

**Issue by firomero** [christianalfoni/flux-angular#63]
What is the best way for updating an object in a collection from the store?
Also I want to know how to share the stores between controllers?

**Comment by jrust** [comment]
To update an object in a collection I usually key it by some sort of unique id. e.g.:
```javascript
flux.dispatch('UPDATE_ITEM', { id: 1, name: 'foo' });
```

and in the store
```javascript
initialize: function() {
  this.state = this.immutable({ items: [] });
},
handlers: { UPDATE_ITEM: 'setItem' },
setItem: function(payload) {
  this.state.select('items', { id: payload.id }).set('name', payload.name);
}
```

See the docs on [baobab](https://github.com/Yomguithereal/baobab), specifically on polymorphisms for all the ways there are to get at your data to update it.

Sharing stores is just a matter of injecting them into multiple controllers.  Like any angular service they are singletons and can be injected anywhere.
