### ISSUE TITLE
Some $listenTo callbacks run outside of the digest cycle when Baobao is in asynchronous mode

### ISSUE THREAD

**Issue by afiedler** [christianalfoni/flux-angular#66]
I've been chasing down a bug with directives not updating with flux-angular, and I think the root cause of the problem is that baobao's asynchronous mode does not work well with Angular's digest cycle.

This is in a fairly complex app, so it will be hard to make a test case, but basically I have something like this:

``` js
function updateFilterDescriptionFromStore () {
   console.log('$rootScope.$$phase: ' + $rootScope.$$phase);
   $scope.filterDescription = _.keys(MyStore.getFilter()).join(', ');
}

$scope.$listenTo(MyStore, ['filter'], updateFilterDescriptionFromStore);
```

When I change the `filter` cursor through other parts of the app (using `flux.dispatch`), I get this in the console:

```
$rootScope.$$phase: $digest
$rootScope.$$phase: $digest
$rootScope.$$phase: null
```

Sometimes it is called in a digest cycle and sometimes it isn't.

I think what is going on here is that when baobao is in `asynchronous: true` mode, it is waiting to emit the `update` event (which then calls the `$listenTo` callback) until the next browser tick. It does this with `setTimeout(() => this.commit(), 0)` [here](https://github.com/Yomguithereal/baobab/blob/9c8765a57093ca7823f05450674ec8b4b5e66b21/src/baobab.js#L443).

Sometimes `this.commit()` is called while a digest cycle is happening, and sometimes it isn't.

I know I could disable async mode, but it makes things much faster when there are many updates to the store at once.

What I ended up doing is wrapping all of my `$scope.$listenTo` callbacks in `$scope.$asyncApply` like this:

``` js
function updateFilterDescriptionFromStore () {
   $scope.$asyncApply(function () {
      console.log('$rootScope.$$phase: ' +$rootScope.$$phase);
      $scope.filterDescription = _.keys(MyStore.getFilter()).join(', ');
   });
}

$scope.$listenTo(MyStore, ['filter'], updateFilterDescriptionFromStore);
```

That seems to fix the issue, but it is awkward and easy to forget to do that.

Is there a better way to fix this problem? Alternatively, I could attempt to make a PR that calls the `$listenTo` callbacks in `$scope.$applyAsync` automatically. What do you think of that solution?

**Comment by jrust** [comment]
Great find and I think that could be a solid solution. I think, like you, we haven't seen this problem surface b/c our app is quite large, but on a smaller apps there have been reports of this issue.  I think the applyAsync idea could work, I'll try and test it out today to ensure it doesn't lead to digest or performance issues.

**Comment by afiedler** [comment]
@jrust, I made a PR that implements a new `fluxProvider.useApplyAsync()` method. You can use that method to optionally enable `$applyAsync`-wrapping globally.

I haven't seen any performance impact from this, but the app I'm working on doesn't need very high performance. Angular's `$http` service does something similar, and from reading up on that, it seems like `$applyAsync` can introduce ~10ms of lag. However, that would be the total amount for all callbacks using $applyAsync, not for each one.
