### ISSUE TITLE
Latest releases are not available via NPM

### ISSUE THREAD

**Issue by mattduggan** [christianalfoni/flux-angular#68]
I'd like to use the latest release (3.1.4) of flux-angular to make use of the $evalAsync option. However, the latest version of flux-angular available as a node package is 3.0.0. 

`npm show flux-angular@* version`

Please let me know if it would be possible to publish this to the npm registry, or if I may help.

**Comment by mattduggan** [comment]
@jrust

**Comment by jrust** [comment]
ah, thx for finding that. published!
