### ISSUE TITLE
webpack2 report error

### ISSUE THREAD

**Issue by mafeifan** [christianalfoni/flux-angular#69]
Hi,

when I use webpack2 and require("flux-angular") I got the error `Cannot assign to read only property 'exports' of object`.
the reason is here #https://github.com/webpack/webpack/issues/4039
mix  import and module.exports.
so I changed L223 `module.exports = 'flux';` to  `export { flux }`  in flux-angular file and it is working
`

**Comment by jrust** [comment]
Interesting.  The release, which includes that module.exports line, is being produced with `browserify` (full command is in `package.json`).  From the issue referenced it appears that maybe it can be solved by changing the `babelify` options, but I wasn't able to get it to take.  If you're able to get it working let me know and I can update the deploy command.

**Comment by jrust** [comment]
Fixed by 52ea2ed7a98946a943cbbb89f89eb89d7effdbc3
