### ISSUE TITLE
documentation: "mixin" instead of "mixins"

### ISSUE THREAD

**Issue by ericmcgregor** [christianalfoni/flux-angular#7]
Hey, i noticed that you're using "mixin" in your example instead of "mixins"

    return flux.store({
            mixin: [MyMixin],
            todos: [],

It took me a minute to figure out why the mixins weren't working.  You need to change that to "mixins".

**Comment by christianalfoni** [comment]
Hi @ericmcgregor and thanks so much for pointing that out, it has been fixed!

**Comment by ericmcgregor** [comment]
Thanks!  also, great job on the library!
