### ISSUE TITLE
QUESTION: How to attach store from another module?

### ISSUE THREAD

**Issue by rodush** [christianalfoni/flux-angular#71]
Hi Christian!
I'm migrating our codebase from flux-angular v2.4 to 3.0.1 and I faced a big issue.
In version v2.4 in docs it was possible to build stores as a hashmap:
```js
...
.factory('Stores', () => {
  return {
     'StoreA' => flux.createStore('A', {}),
    ....
  };
});
```
That allowed our developers to make an architectural mistake, and some modules appeared to be dependant on stores defined in an another module.
No I see the only recommended way is to use "store()" which will automatically register a store during module initialization.

What is the right way to manually register a store in a module?

**Comment by jrust** [comment]
Because of the need to keep track of stores the only way to create them is via `angular.store`.  Can you use that?
