### ISSUE TITLE
Question: cloning of stores - performance

### ISSUE THREAD

**Issue by sebakerckhof** [christianalfoni/flux-angular#8]
I'm just exploring flux and flux-angular for the first time and haven't looked to deep into the source code, but when reading this: "When emitChange is run all values on state will be cloned to bound scopes." 
I wondered if I should worry about performance when the state has large objects/arrays and a lot of bound scopes?

**Comment by christianalfoni** [comment]
Hi @sebakerckhof :-)

Normally you do not have to worry about that. The reason is the callback:

```javascript
.controller('MyCtrl', function ($scope, MyStore) {
  MyStore.bindTo($scope, function () {
    $scope.items = MyStore.getItems();
  });
})
```
Lets say your store has 10.000 items. The getItems() method probably does not return all 10.000 but a subset based on paging, a filter or something. The performance hit in regards of cloning is in what your controllers "drag out" from the store, not what is inside your store :-)

Please let me know if you would like me to elaborate further

**Comment by SuperheroicCoding** [comment]
Here you can see an colorflux example with up to 10000 items: 
Just use the range input to raise number of resolved colorfields. 

http://run.plnkr.co/plunks/ysyWtM/

I just made some experiments with your awesome module. I love the feeling while implementing. It feet much better then the MVC way in angular.

**Comment by christianalfoni** [comment]
Haha, that must be the most awesome demo ever ;-)

Thanks for the feedback! It is really interesting to see how the flux pattern fits better to more modern apps. I have actually a video introduction to a framework I built which talks a bit about the history of MVC and how flux fixes that. Think you will find it interesting being an Angular developer :-)

https://www.youtube.com/watch?v=plUN2L4Ak14. Framework is at www.jflux.io if you would be interested.

**Comment by SuperheroicCoding** [comment]
Thanks for the video. I have learned a lot. My hystory is mostly with the Java web stack. The last years I had some projects with angularjs. Now using the flux architecture solves a lot of problems that often occure to me about were to put stuff, who is responsible and how to propagate changes. I am looking forward how it scales when the app grows. I am curious and a little worried about how big stores feel and behave in terms of clean code and testability. Awesome times for web development!

**Comment by sebakerckhof** [comment]
Thanks for the answer and the video, great resource.

2015-01-07 8:11 GMT+01:00 SuperheroicCoding <notifications@github.com>:
